services:
  lgtm:
    image: grafana/otel-lgtm:latest
    ports:
      - "3000:3000" # Grafana UI
      - "4317:4317" # OTLP gRPC (traces)
      - "4318:4318" # OTLP HTTP (traces)
      - "9009:9009" # Prometheus remote write for metrics
      - "3100:3100" # Loki logs (if needed)

  promtail:
    image: grafana/promtail:latest
    volumes:
      - /var/log/journal:/var/log/journal:ro
      - ./promtail-config.yaml:/etc/promtail/config.yaml
    command: -config.file=/etc/promtail/config.yaml
    depends_on:
      - lgtm

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://lgtm
    depends_on:
      - lgtm
    logging:
      driver: journald
      options:
        tag: "{{.Name}}"
