services:
  lgtm:
    image: grafana/otel-lgtm:0.11.6
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: unless-stopped

  alloy:
    image: grafana/alloy:v1.10.0
    ports:
      - "12345:12345"
    volumes:
      - ./infra/alloy/config.alloy:/etc/alloy/config.alloy:ro
    command: >
      run --server.http.listen-addr=0.0.0.0:12345
          --storage.path=/var/lib/alloy/data
          /etc/alloy/config.alloy
    depends_on:
      - lgtm

  app:
    build: ./app
    ports:
      - "8080:8080"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://lgtm
    depends_on:
      - lgtm
      - alloy
    logging:
      driver: journald
