server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://lgtm:3100/loki/api/v1/push

scrape_configs:
  - job_name: podman-journald
    journal:
      path: /var/log/journal
      labels:
        app: simple_lgtm_app
    relabel_configs:
      - source_labels: ['__journal__systemd_unit']
        target_label: 'unit'
      - source_labels: ['__journal__hostname']
        target_label: 'host'
